INSERT INTO COUNTRY (ID, NAME) VALUES (1, 'Brazil');
INSERT INTO COUNTRY (ID, NAME) VALUES (2, 'United Kingdom');

INSERT INTO CONTACT_TYPE (ID, NAME) VALUES (1, 'Mobile');
INSERT INTO CONTACT_TYPE (ID, NAME) VALUES (2, 'Phone');
INSERT INTO CONTACT_TYPE (ID, NAME) VALUES (3, 'E-mail');

INSERT INTO PROFESSION (ID, NAME) VALUES (1, 'Software Developer');
INSERT INTO PROFESSION (ID, NAME) VALUES (2, 'Lawyer');
INSERT INTO PROFESSION (ID, NAME) VALUES (3, 'Teacher');
INSERT INTO PROFESSION (ID, NAME) VALUES (4, 'QA Analyst');
INSERT INTO PROFESSION (ID, NAME) VALUES (5, 'Car Seller');
INSERT INTO PROFESSION (ID, NAME) VALUES (6, 'Engineer');

INSERT INTO PERSON (ID, NAME, GENDER, BIRTH, PROFESSION, ADDRESS, CITY, STATE, ZIP_CODE, COUNTRY)
VALUES (1, 'Alexandre', 'M', '1986-12-16', 1, 'Avenida Paes de Barros, 1152', 'São Paulo', 'SP', '03356-542', 1);

INSERT INTO CONTACT (PERSON, CONTACT_TYPE, VALUE) VALUES (1, 1, '555-5652');
INSERT INTO CONTACT (PERSON, CONTACT_TYPE, VALUE) VALUES (1, 2, '555-7785');
INSERT INTO CONTACT (PERSON, CONTACT_TYPE, VALUE) VALUES (1, 3, 'alexandre.queiroz@oracle.com');